properties([
    parameters([
        choice(
            name: 'typeParam',
            choices: ['Integer Squares', 'Non-Integer Squares'],
            description: 'Выберите тип: Integer Squares (целые квадраты) или Non-Integer Squares (нецелые квадраты)'
        ),
        string(
            name: 'integer_squares_param',
            description: 'Введите число, для которого нужно вычислить корень'
        )
    ])
])

pipeline {
    agent { label 'specific-agent' }

    stages {
        stage('Input Validation') {
            steps {
                script {
                    if (!params.integer_squares_param.isDouble()) {
                        error("Значение должно быть числом")
                    }
                }
            }
        }

        stage('Root Calculation') {
            steps {
                script {
                    def type = params.typeParam
                    double number = Double.parseDouble(params.integer_squares_param)
                    double result = calculateSquareRoot(number)

                    validateRoot(type, result)

                    echo String.format("Корень из %.2f равен %.2f", number, result)
                }
            }
        }
    }
    
    post {
        always {
            echo 'Завершение расчета, ресурсы освобождены'
        }
        success {
            echo 'Расчет выполнен успешно!'
        }
        failure {
            echo 'Произошла ошибка в процессе расчета.'
        }
    }
}

@NonCPS
def calculateSquareRoot(double number) {
    return Math.sqrt(number)
}

@NonCPS
def validateRoot(String type, double result) {
    if (type == 'Integer Squares' && !(result % 1 == 0)) {
        throw new IllegalArgumentException("Результат корня не является целым числом, что не соответствует типу 'Integer Squares'")
    } else if (type == 'Non-Integer Squares' && result % 1 == 0) {
        throw new IllegalArgumentException("Результат корня является целым числом, что не соответствует типу 'Non-Integer Squares'")
    }
}
