properties([
    parameters([
        choice(
            name: 'typeParam',
            choices: ['Integer Squares', 'Non-Integer Squares'],
            description: 'Выберите тип'
        ),
        string(
            name: 'integer_squares_param',
            description: 'Введите число'
        )
    ])
])

pipeline {
    agent any
    stages {
        stage('Input') {
            steps {
                script {
                    def number = params.integer_squares_param
                    echo "Введенное число: ${number}"
                }
            }
        }
        
        stage('Calculation') {
            steps {
                script {
                    try {
                        def number = params.integer_squares_param
                        double parsedNumber = Double.parseDouble(number)
                        double result = Math.sqrt(parsedNumber)
                        echo "Корень из ${number} равен ${result}"
                        currentBuild.description = "Результат: ${result}"
                    } catch (Exception e) {
                        error "Ошибка при расчете: ${e.message}"
                    }
                }
            }
        }

        stage('Validation') {
            steps {
                script {
                    def type = params.typeParam
                    def result = currentBuild.description.split(': ')[1] as double

                    if (type == 'Integer Squares' && result % 1 != 0) {
                        error "Ошибка: Результат корня не является целым числом, что не соответствует типу 'Integer Squares'"
                    } else if (type == 'Non-Integer Squares' && result % 1 == 0) {
                        error "Ошибка: Результат корня является целым числом, что не соответствует типу 'Non-Integer Squares'"
                    }
                    echo "Валидация прошла успешно!"
                }
            }
        }
    }
    
    post {
        success {
            echo 'Расчет завершен успешно!'
        }
        failure {
            echo 'Произошла ошибка при расчете.'
        }
    }
}
